# Generated by Django 2.2 on 2019-05-09 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eabmodel', '0001_initial'),
        ('rubrica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('presentation_time', models.TimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eabmodel.Course')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rubrica.Rubric')),
            ],
            options={
                'unique_together': {('name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TeamEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion.Evaluation')),
                ('presenter', models.ManyToManyField(to='eabmodel.Student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eabmodel.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamEvaluationGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_detail', models.TextField()),
                ('final_grade', models.FloatField()),
                ('comment', models.TextField()),
                ('team_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.TeamEvaluation')),
            ],
        ),
    ]
