# Generated by Django 2.2 on 2019-05-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('suggested_presentation_time', models.TimeField()),
                ('n_compliance_lvl', models.PositiveSmallIntegerField()),
                ('n_evaluated_aspect', models.PositiveSmallIntegerField()),
                ('rubric', models.TextField()),
                ('completed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
