# Generated by Django 2.2 on 2019-05-09 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='código del curso', max_length=7, verbose_name='código')),
                ('name', models.CharField(help_text='nombre del curso', max_length=150, verbose_name='nombre')),
                ('section', models.PositiveSmallIntegerField(default=1, help_text='sección del curso', verbose_name='sección')),
                ('year', models.PositiveSmallIntegerField(default=2019, help_text='año que se dicta el curso', verbose_name='año')),
                ('semester', models.CharField(choices=[('Otoño', 'Otoño'), ('Primavera', 'Primavera'), ('Verano', 'Verano')], default='Otoño', help_text='semestre que se dicta el curso', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'unique_together': {('code', 'section', 'year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eabmodel.Course')),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eabmodel.Course')),
            ],
            options={
                'unique_together': {('name', 'course')},
            },
        ),
        migrations.CreateModel(
            name='StudentAtTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('left_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eabmodel.Student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eabmodel.Team')),
            ],
        ),
    ]
